/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    public static void main(String[] args) {
        Mobile mobile = new Mobile();
        Iphone iphone = new Iphone();
        AndroidMobile androidMobile = new AndroidMobile();
        mobile.makeCall("i am a mobile");
        iphone.makeCall("i am a iphone");
        androidMobile.makeCall("i am a androidMobile");
    }
}
