/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    public static void main(String[] args) {
        Mobile mobile = new Mobile();
        Iphone iphone = new Iphone("iphoneX","white","Iphone");
        AndroidMobile androidMobile = new AndroidMobile("Mix2","black", "Xiaomi");
        mobile.makeCall("i am a mobile");
        iphone.makeCall("i am an iphone");
        androidMobile.makeCall("i am an androidMobile");
        androidMobile.printInfo();

        Person person = new Person(androidMobile, "eric.li");
        person.sendMessage("i sent message by androidMobile");
        person.sendMessage("i sent a long message by androidMobile may can not be sent");

        person.changePhone(iphone);
        person.sendMessage("i sent message by iphoneMobile");
        person.sendMessage("i sent a long message by iphoneMobile may can not be sent");
    }
}
